title: International Press journal CIS author support
description: TeX related material for the manuscript preparation for the
             International Press journal Communications in Information and Systems
             (CIS)
show_downloads: true
theme: jekyll-theme-tactile
